### ISSUE TITLE
github API 테스트

### ISSUE THREAD

**Issue by leedo97y** [leedo97y/fire-test#4]
## Todo

- [x] 사용자 정보 저장하기 및 github API를 사용하여 username 가져오기
- [x] 사용자 정보 사용하여 github repo 가져오기
- [x] 폴더 클릭시 하위 폴더 / 파일 불러오도록 하기
- [x] 폴더 버튼 및 파일 버튼 구분하기
- [ ] 파일 버튼 클릭 시 인코딩 된 content 부분 찾아서 디코딩 해보기
